### ISSUE TITLE
Hashtags are not correctly highlighted

### ISSUE THREAD

**Issue by benaryorg** [veskuh/Tweetian#184] opened 2015-01-11 11:12 UTC
If a hashtag is preceded by a non whitespace, then the wort is correctly marked as a hashtag, but the last two letters are repeated, once as a part of the hashtag and once as unhighlighted garbage directly after the hashtag.

**Comment by veskuh** [comment] 2015-01-11 12:40
Can you give me an example? I tried "Test 2. Last#test I promise" without an issue. Also what Sailfish version and Tweetian version?

**Comment by benaryorg** [comment] 2015-01-25 17:03
I used the search function to find some Tweets.

I am answering via email so I hope the images will be sent correctly.

EDIT: The whole mail has not been sent from my Jolla.

**Comment by benaryorg** [comment] 2015-01-25 17:14
The pictures:

![a.png](https://cloud.githubusercontent.com/assets/6145260/5892401/520ad40e-a4bd-11e4-99b9-f6b66a99e10e.png)
![b.png](https://cloud.githubusercontent.com/assets/6145260/5892402/521d9fbc-a4bd-11e4-86ec-3791bf578c02.png)
![c.png](https://cloud.githubusercontent.com/assets/6145260/5892404/52451de4-a4bd-11e4-8fdb-e6050a82c9b5.png)
![d.png](https://cloud.githubusercontent.com/assets/6145260/5892403/5242760c-a4bd-11e4-9e27-5b8b770e7e94.png)

**Comment by veskuh** [comment] 2015-02-04 09:19
Yes, now I've been able to replicate this with search.

**Comment by veskuh** [comment] 2015-04-03 15:00
This happens when tweet includes emoticons. Start and end indexes provided by twitter do not point correctly to hashags location. Unsure still if the problem is in the Twitter API, Qt, or Tweetian's code. No fix yet.

**Comment by veskuh** [comment] 2015-08-05 07:00
released in 2.0.7

**Closed as completed by veskuh** 2015-08-05 07:00 UTC
