### ISSUE TITLE
Show conversations

### ISSUE THREAD

**Issue by jukey** [veskuh/Tweetian#156] opened 2014-06-17 08:44 UTC
All native twitter apps allow to see all the tweets that are related to a specific tweet. If I open a tweet I see all previous tweets even if I do not follow the sender. If there are answers to a specific tweet I also can see the tweets without following the answering account(s).

In Tweetian these related tweets should appear (as pictures do) as soon as I open a tweet.

**Comment by veskuh** [comment] 2014-06-27 10:35
duplicate of #68

**Closed as completed** 2014-06-27 10:35 UTC
