### ISSUE TITLE
timestamps are missing after update to Uitukka

### ISSUE THREAD

**Issue by Morpog** [veskuh/Tweetian#167] opened 2014-10-22 19:57 UTC
![20141022215532](https://cloud.githubusercontent.com/assets/1842433/4743206/9ff0ab2c-5a25-11e4-994f-b8f439f9f4e9.png)

**Comment by schmittlauch** [comment] 2014-10-22 20:19
Duplicate of #163

**Comment by veskuh** [comment] 2014-10-23 07:46
Yep, duplicate.

**Closed as completed by veskuh** 2014-10-23 07:46 UTC
