### ISSUE TITLE
Show the associated replied-to tweet always

### ISSUE THREAD

**Issue by harriha** [veskuh/Tweetian#85] opened 2014-02-12 21:36 UTC
(commenting based on the Sailfish version)

Seems that if opening a reply to a tweet which isn't available locally already, the original parent tweet doesn't get downloaded at all. This is bit odd behavior, I'd expect to see the associated parent tweet always, also if it wouldn't be part of my timeline normally.

**Comment by Morpog** [comment] 2014-02-28 09:59
this sounds like a duplicate of #68

**Comment by harriha** [comment] 2014-03-08 17:28
@Morpog Yes, with the addition that even if I'm following the person who the reply was send to, the original tweet won't show unless it is cached locally already. Maybe somehow be related to #84 as well.

**Comment by veskuh** [comment] 2014-03-16 14:20
Closed as duplicate of #68

**Closed as completed** 2014-03-16 14:19 UTC
